apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eventing.knative.dev/release: {{ .Chart.AppVersion }}
  name: eventing-controller
  namespace: knative-eventing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eventing.knative.dev/release: {{ .Chart.AppVersion }}
  name: eventing-webhook
  namespace: knative-eventing
