apiVersion: v1
kind: Service
metadata:
  labels:
    app: sources-controller
    eventing.knative.dev/release: {{ .Chart.AppVersion }}
    {{- with .Values.global.serviceLabels }}
    {{ toYaml . | indent 4 | trim }}
    {{- end }}
  name: sources-controller
  namespace: knative-eventing
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: sources-controller
