apiVersion: v1
kind: Service
metadata:
  labels:
    eventing.knative.dev/release: {{ .Chart.AppVersion }}
    role: eventing-webhook
    {{- with .Values.global.serviceLabels }}
    {{ toYaml . | indent 4 | trim }}
    {{- end }}
  name: eventing-webhook
  namespace: knative-eventing
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    role: eventing-webhook
