apiVersion: v1
kind: Service
metadata:
  labels:
    contrib.eventing.knative.dev/release: {{ .Chart.AppVersion }}
    control-plane: github-controller-manager
    {{- with .Values.global.serviceLabels }}
    {{ toYaml . | indent 4 | trim }}
    {{- end }}
  name: github-controller
  namespace: knative-sources
spec:
  ports:
  - port: 443
  selector:
    control-plane: github-controller-manager
