apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    contrib.eventing.knative.dev/release: {{ .Chart.AppVersion }}
    control-plane: github-controller-manager
  name: github-controller-manager
  namespace: knative-sources
spec:
  selector:
    matchLabels:
      control-plane: github-controller-manager
  serviceName: github-controller-manager
  template:
    metadata:
      labels:
        control-plane: github-controller-manager
    spec:
      containers:
      - env:
        - name: GH_RA_IMAGE
          value: gcr.io/knative-releases/github.com/knative/eventing-contrib/contrib/github/cmd/receive_adapter@sha256:092aebac831ff1117d80ef7f0d6e6cf52ecc2cfa49f2ced6b77a5ee564372a3d
        image: index.docker.io/chhsiao/controller-936c75cbb51cf5f160954f2cab4d0b6c:{{ .Chart.AppVersion }}
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: github-controller-manager
      terminationGracePeriodSeconds: 10
