apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller
    serving.knative.dev/release: {{ .Chart.AppVersion | quote }}
    {{- with .Values.global.serviceLabels }}
    {{ toYaml . | indent 4 | trim }}
    {{- end }}
  name: controller
  namespace: knative-serving
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: controller
