apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
    serving.knative.dev/release: {{ .Chart.AppVersion | quote }}
    {{- with .Values.global.serviceLabels }}
    {{ toYaml . | indent 4 | trim }}
    {{- end }}
  name: webhook
  namespace: knative-serving
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    role: webhook
